import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import BrandLayout from '../components/BrandLayout';
import DeployModal from '../components/deploy/DeployModal';
import { Card } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../components/ui/select';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '../components/ui/table';
import {
  GitBranch, CheckCircle, Clock, AlertCircle, Search,
  Filter, ArrowLeft, Package, Users, ShoppingCart, BarChart3
} from 'lucide-react';
import { useLocation } from 'wouter';

interface DeployCommit {
  id: string;
  tool: 'crm' | 'wms' | 'pos' | 'analytics';
  resourceType: string;
  resourceId: string;
  version: string;
  status: 'pending' | 'deployed' | 'failed';
  metadata: any;
  createdAt: string;
  autoGenerated: boolean;
}

const withAlpha = (hslColor: string, alpha: number) => {
  if (hslColor.includes('var(')) {
    const lastParenIndex = hslColor.lastIndexOf(')');
    return hslColor.slice(0, lastParenIndex) + ` / ${alpha})`;
  } else {
    return hslColor.replace('hsl(', 'hsla(').replace(')', `, ${alpha})`);
  }
};

export default function CommitBrowser() {
  const [, setLocation] = useLocation();
  const [selectedTool, setSelectedTool] = useState<string>('all');
  const [selectedStatus, setSelectedStatus] = useState<string>('all');
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCommit, setSelectedCommit] = useState<DeployCommit | null>(null);

  const { data: commits, isLoading } = useQuery<{ data: DeployCommit[] }>({
    queryKey: ['/brand-api/deploy/commits']
  });

  const toolIcons = {
    crm: Users,
    wms: Package,
    pos: ShoppingCart,
    analytics: BarChart3
  };

  const toolColors = {
    crm: 'hsl(25, 95%, 53%)',
    wms: 'hsl(274, 65%, 46%)',
    pos: 'hsl(142, 76%, 36%)',
    analytics: 'hsl(220, 90%, 56%)'
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'deployed':
        return 'hsl(142, 76%, 36%)';
      case 'pending':
        return 'hsl(38, 92%, 50%)';
      case 'failed':
        return 'hsl(0, 84%, 60%)';
      default:
        return 'hsl(var(--muted-foreground))';
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'deployed':
        return CheckCircle;
      case 'pending':
        return Clock;
      case 'failed':
        return AlertCircle;
      default:
        return Clock;
    }
  };

  const filteredCommits = commits?.data?.filter(commit => {
    const matchesTool = selectedTool === 'all' || commit.tool === selectedTool;
    const matchesStatus = selectedStatus === 'all' || commit.status === selectedStatus;
    const matchesSearch = searchTerm === '' ||
      commit.resourceType.toLowerCase().includes(searchTerm.toLowerCase()) ||
      commit.version.toLowerCase().includes(searchTerm.toLowerCase()) ||
      commit.resourceId.toLowerCase().includes(searchTerm.toLowerCase());
    
    return matchesTool && matchesStatus && matchesSearch;
  }) || [];

  return (
    <BrandLayout>
      <div style={{ width: '100%', padding: '0 2rem' }}>
        {/* Header */}
        <div style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          marginBottom: '2rem'
        }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.5rem' }}>
              <Button
                variant="ghost"
                onClick={() => setLocation('/deploy-center')}
                style={{ padding: '0.5rem' }}
                data-testid="button-back-to-overview"
              >
                <ArrowLeft size={20} />
              </Button>
              <h1 style={{
                fontSize: '2rem',
                fontWeight: '700',
                color: 'hsl(var(--foreground))',
                display: 'flex',
                alignItems: 'center',
                gap: '0.75rem'
              }}
              data-testid="heading-commit-browser">
                <GitBranch size={32} style={{ color: 'hsl(var(--brand-orange))' }} />
                Commit Browser
              </h1>
            </div>
            <p style={{
              fontSize: '1rem',
              color: 'hsl(var(--muted-foreground))'
            }}
            data-testid="text-browser-subtitle">
              Visualizza e gestisci tutti i deployment commits
            </p>
          </div>
        </div>

        {/* Filters Card */}
        <Card style={{
          background: 'rgba(255, 255, 255, 0.08)',
          backdropFilter: 'blur(24px) saturate(180%)',
          WebkitBackdropFilter: 'blur(24px) saturate(180%)',
          border: '1px solid rgba(255, 255, 255, 0.25)',
          borderRadius: '12px',
          padding: '1.5rem',
          marginBottom: '2rem'
        }}
        data-testid="card-filters">
          <div style={{
            display: 'flex',
            alignItems: 'center',
            gap: '0.75rem',
            marginBottom: '1rem'
          }}>
            <Filter size={20} style={{ color: 'hsl(var(--brand-orange))' }} />
            <h3 style={{
              fontSize: '1.125rem',
              fontWeight: '600',
              color: 'hsl(var(--foreground))'
            }}
            data-testid="heading-filters">
              Filtri
            </h3>
          </div>

          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
            gap: '1rem'
          }}>
            {/* Search Input */}
            <div>
              <label style={{
                display: 'block',
                fontSize: '0.875rem',
                fontWeight: '500',
                marginBottom: '0.5rem',
                color: 'hsl(var(--foreground))'
              }}
              data-testid="label-search">
                Cerca
              </label>
              <div style={{ position: 'relative' }}>
                <Search
                  size={16}
                  style={{
                    position: 'absolute',
                    left: '0.75rem',
                    top: '50%',
                    transform: 'translateY(-50%)',
                    color: 'hsl(var(--muted-foreground))'
                  }}
                />
                <Input
                  placeholder="Type, Version, ID..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  style={{ paddingLeft: '2.5rem' }}
                  data-testid="input-search"
                />
              </div>
            </div>

            {/* Tool Filter */}
            <div>
              <label style={{
                display: 'block',
                fontSize: '0.875rem',
                fontWeight: '500',
                marginBottom: '0.5rem',
                color: 'hsl(var(--foreground))'
              }}
              data-testid="label-tool">
                Tool
              </label>
              <Select value={selectedTool} onValueChange={setSelectedTool}>
                <SelectTrigger data-testid="select-tool-trigger">
                  <SelectValue placeholder="Tutti" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all" data-testid="select-tool-all">Tutti</SelectItem>
                  <SelectItem value="crm" data-testid="select-tool-crm">CRM</SelectItem>
                  <SelectItem value="wms" data-testid="select-tool-wms">WMS</SelectItem>
                  <SelectItem value="pos" data-testid="select-tool-pos">POS</SelectItem>
                  <SelectItem value="analytics" data-testid="select-tool-analytics">Analytics</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Status Filter */}
            <div>
              <label style={{
                display: 'block',
                fontSize: '0.875rem',
                fontWeight: '500',
                marginBottom: '0.5rem',
                color: 'hsl(var(--foreground))'
              }}
              data-testid="label-status">
                Status
              </label>
              <Select value={selectedStatus} onValueChange={setSelectedStatus}>
                <SelectTrigger data-testid="select-status-trigger">
                  <SelectValue placeholder="Tutti" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all" data-testid="select-status-all">Tutti</SelectItem>
                  <SelectItem value="pending" data-testid="select-status-pending">Pending</SelectItem>
                  <SelectItem value="deployed" data-testid="select-status-deployed">Deployed</SelectItem>
                  <SelectItem value="failed" data-testid="select-status-failed">Failed</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* Results Count */}
          <div style={{
            marginTop: '1rem',
            padding: '0.75rem',
            background: withAlpha('hsl(var(--brand-orange))', 0.1),
            borderRadius: '8px',
            fontSize: '0.875rem',
            color: 'hsl(var(--foreground))'
          }}
          data-testid="text-results-count">
            <strong>{filteredCommits.length}</strong> commit{filteredCommits.length !== 1 ? 's' : ''} trovat{filteredCommits.length !== 1 ? 'i' : 'o'}
          </div>
        </Card>

        {/* Commits Table */}
        <Card style={{
          background: 'rgba(255, 255, 255, 0.08)',
          backdropFilter: 'blur(24px) saturate(180%)',
          WebkitBackdropFilter: 'blur(24px) saturate(180%)',
          border: '1px solid rgba(255, 255, 255, 0.25)',
          borderRadius: '12px',
          overflow: 'hidden'
        }}
        data-testid="card-commits-table">
          {isLoading ? (
            <div style={{ padding: '3rem', textAlign: 'center' }}>
              <p style={{ color: 'hsl(var(--muted-foreground))' }} data-testid="text-loading">
                Caricamento commits...
              </p>
            </div>
          ) : filteredCommits.length === 0 ? (
            <div style={{ padding: '3rem', textAlign: 'center' }}>
              <p style={{ color: 'hsl(var(--muted-foreground))' }} data-testid="text-no-results">
                Nessun commit trovato con i filtri selezionati
              </p>
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead data-testid="th-tool">Tool</TableHead>
                  <TableHead data-testid="th-type">Resource Type</TableHead>
                  <TableHead data-testid="th-id">Resource ID</TableHead>
                  <TableHead data-testid="th-version">Version</TableHead>
                  <TableHead data-testid="th-status">Status</TableHead>
                  <TableHead data-testid="th-created">Created At</TableHead>
                  <TableHead data-testid="th-auto">Auto</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredCommits.map((commit) => {
                  const ToolIcon = toolIcons[commit.tool];
                  const StatusIcon = getStatusIcon(commit.status);
                  
                  return (
                    <TableRow
                      key={commit.id}
                      onClick={() => setSelectedCommit(commit)}
                      style={{
                        cursor: 'pointer',
                        transition: 'background 0.2s'
                      }}
                      data-testid={`row-commit-${commit.id}`}
                    >
                      <TableCell data-testid={`cell-tool-${commit.id}`}>
                        <div style={{
                          display: 'flex',
                          alignItems: 'center',
                          gap: '0.5rem'
                        }}>
                          <div style={{
                            width: '32px',
                            height: '32px',
                            borderRadius: '6px',
                            background: withAlpha(toolColors[commit.tool], 0.2),
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center'
                          }}>
                            <ToolIcon size={16} style={{ color: toolColors[commit.tool] }} />
                          </div>
                          <span style={{
                            fontWeight: '600',
                            color: toolColors[commit.tool],
                            textTransform: 'uppercase'
                          }}>
                            {commit.tool}
                          </span>
                        </div>
                      </TableCell>
                      <TableCell data-testid={`cell-type-${commit.id}`}>
                        <span style={{ fontWeight: '500' }}>{commit.resourceType}</span>
                      </TableCell>
                      <TableCell data-testid={`cell-id-${commit.id}`}>
                        <code style={{
                          fontSize: '0.875rem',
                          padding: '0.25rem 0.5rem',
                          background: 'rgba(0, 0, 0, 0.05)',
                          borderRadius: '4px'
                        }}>
                          {commit.resourceId.substring(0, 8)}...
                        </code>
                      </TableCell>
                      <TableCell data-testid={`cell-version-${commit.id}`}>
                        <span style={{
                          fontFamily: 'monospace',
                          fontSize: '0.875rem',
                          fontWeight: '600'
                        }}>
                          {commit.version}
                        </span>
                      </TableCell>
                      <TableCell data-testid={`cell-status-${commit.id}`}>
                        <div style={{
                          display: 'inline-flex',
                          alignItems: 'center',
                          gap: '0.5rem',
                          padding: '0.25rem 0.75rem',
                          borderRadius: '9999px',
                          background: withAlpha(getStatusColor(commit.status), 0.15),
                          color: getStatusColor(commit.status),
                          fontSize: '0.75rem',
                          fontWeight: '600'
                        }}>
                          <StatusIcon size={14} />
                          {commit.status}
                        </div>
                      </TableCell>
                      <TableCell data-testid={`cell-created-${commit.id}`}>
                        <span style={{
                          fontSize: '0.875rem',
                          color: 'hsl(var(--muted-foreground))'
                        }}>
                          {new Date(commit.createdAt).toLocaleString('it-IT')}
                        </span>
                      </TableCell>
                      <TableCell data-testid={`cell-auto-${commit.id}`}>
                        {commit.autoGenerated ? (
                          <span style={{
                            fontSize: '0.75rem',
                            padding: '0.125rem 0.5rem',
                            background: withAlpha('hsl(220, 90%, 56%)', 0.15),
                            color: 'hsl(220, 90%, 56%)',
                            borderRadius: '4px',
                            fontWeight: '600'
                          }}>
                            AUTO
                          </span>
                        ) : (
                          <span style={{
                            fontSize: '0.75rem',
                            color: 'hsl(var(--muted-foreground))'
                          }}>
                            Manual
                          </span>
                        )}
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          )}
        </Card>

        {/* Deploy Modal - Full Implementation */}
        <DeployModal
          commit={selectedCommit}
          open={!!selectedCommit}
          onClose={() => setSelectedCommit(null)}
        />
      </div>
    </BrandLayout>
  );
}
