import { useQuery } from '@tanstack/react-query';
import BrandLayout from '../components/BrandLayout';
import { Card } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { 
  GitBranch, Package, Users, ShoppingCart, BarChart3, 
  Clock, CheckCircle, AlertCircle, Rocket
} from 'lucide-react';
import { useLocation } from 'wouter';

interface DeployCommit {
  id: string;
  tool: 'crm' | 'wms' | 'pos' | 'analytics';
  resourceType: string;
  resourceId: string;
  version: string;
  status: 'pending' | 'deployed' | 'failed';
  metadata: any;
  createdAt: string;
  autoGenerated: boolean;
}

const withAlpha = (hslColor: string, alpha: number) => {
  if (hslColor.includes('var(')) {
    const lastParenIndex = hslColor.lastIndexOf(')');
    return hslColor.slice(0, lastParenIndex) + ` / ${alpha})`;
  } else {
    return hslColor.replace('hsl(', 'hsla(').replace(')', `, ${alpha})`);
  }
};

export default function DeployCenter() {
  const [, setLocation] = useLocation();
  const { data: commits, isLoading } = useQuery<{ data: DeployCommit[] }>({
    queryKey: ['/brand-api/deploy/commits']
  });

  const commitsByTool = {
    crm: commits?.data?.filter(c => c.tool === 'crm').length || 0,
    wms: commits?.data?.filter(c => c.tool === 'wms').length || 0,
    pos: commits?.data?.filter(c => c.tool === 'pos').length || 0,
    analytics: commits?.data?.filter(c => c.tool === 'analytics').length || 0,
  };

  const recentCommits = commits?.data?.slice(0, 10) || [];

  const toolCards = [
    {
      id: 'crm',
      name: 'CRM',
      icon: Users,
      count: commitsByTool.crm,
      color: 'hsl(25, 95%, 53%)',
      description: 'Campagne, Pipeline, Funnel'
    },
    {
      id: 'wms',
      name: 'WMS',
      icon: Package,
      count: commitsByTool.wms,
      color: 'hsl(274, 65%, 46%)',
      description: 'Fornitori, Prodotti, Listini'
    },
    {
      id: 'pos',
      name: 'POS',
      icon: ShoppingCart,
      count: commitsByTool.pos,
      color: 'hsl(142, 76%, 36%)',
      description: 'Configurazioni cassa'
    },
    {
      id: 'analytics',
      name: 'Analytics',
      icon: BarChart3,
      count: commitsByTool.analytics,
      color: 'hsl(220, 90%, 56%)',
      description: 'Report e KPI'
    }
  ];

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'deployed':
        return 'hsl(142, 76%, 36%)';
      case 'pending':
        return 'hsl(38, 92%, 50%)';
      case 'failed':
        return 'hsl(0, 84%, 60%)';
      default:
        return 'hsl(var(--muted-foreground))';
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'deployed':
        return CheckCircle;
      case 'pending':
        return Clock;
      case 'failed':
        return AlertCircle;
      default:
        return GitBranch;
    }
  };

  return (
    <BrandLayout>
      <div style={{
        padding: '2rem',
        maxWidth: '1600px',
        margin: '0 auto'
      }}>
        {/* Header */}
        <div style={{
          marginBottom: '2rem',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center'
        }}>
          <div>
            <h1 style={{
              fontSize: '2rem',
              fontWeight: '700',
              color: 'hsl(var(--foreground))',
              marginBottom: '0.5rem',
              display: 'flex',
              alignItems: 'center',
              gap: '0.75rem'
            }}
            data-testid="heading-deploy-center">
              <GitBranch size={32} style={{ color: 'hsl(var(--brand-orange))' }} />
              Deploy Center
            </h1>
            <p style={{
              fontSize: '1rem',
              color: 'hsl(var(--muted-foreground))'
            }}
            data-testid="text-deploy-subtitle">
              Gestione centralizzata deployment CRM, WMS, POS e Analytics
            </p>
          </div>
          <Button
            onClick={() => setLocation('/deploy-center/commits')}
            data-testid="button-browse-commits"
            style={{
              background: 'linear-gradient(135deg, hsl(25, 95%, 53%), hsl(25, 100%, 60%))',
              color: 'white',
              padding: '0.75rem 1.5rem',
              borderRadius: '8px',
              fontWeight: '600',
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem',
              border: 'none',
              cursor: 'pointer'
            }}
          >
            <Rocket size={20} />
            Browse All Commits
          </Button>
        </div>

        {/* 2x2 Grid - Tool Stats */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
          gap: '1.5rem',
          marginBottom: '2rem'
        }}>
          {toolCards.map(tool => {
            const Icon = tool.icon;
            return (
              <Card
                key={tool.id}
                data-testid={`card-tool-${tool.id}`}
                style={{
                  background: 'rgba(255, 255, 255, 0.08)',
                  backdropFilter: 'blur(24px) saturate(180%)',
                  WebkitBackdropFilter: 'blur(24px) saturate(180%)',
                  border: '1px solid rgba(255, 255, 255, 0.25)',
                  borderRadius: '12px',
                  padding: '1.5rem',
                  position: 'relative',
                  overflow: 'hidden',
                  cursor: 'pointer',
                  transition: 'all 0.3s ease'
                }}
              >
                <div style={{
                  position: 'absolute',
                  top: '-20px',
                  right: '-20px',
                  width: '100px',
                  height: '100px',
                  borderRadius: '50%',
                  background: withAlpha(tool.color, 0.15),
                  filter: 'blur(40px)'
                }} />
                
                <div style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '1rem',
                  marginBottom: '1rem',
                  position: 'relative',
                  zIndex: 1
                }}>
                  <div style={{
                    width: '48px',
                    height: '48px',
                    borderRadius: '10px',
                    background: withAlpha(tool.color, 0.2),
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center'
                  }}>
                    <Icon size={24} style={{ color: tool.color }} />
                  </div>
                  <div>
                    <h3 style={{
                      fontSize: '1.25rem',
                      fontWeight: '700',
                      color: 'hsl(var(--foreground))',
                      marginBottom: '0.25rem'
                    }}
                    data-testid={`text-${tool.id}-name`}>
                      {tool.name}
                    </h3>
                    <p style={{
                      fontSize: '0.875rem',
                      color: 'hsl(var(--muted-foreground))'
                    }}
                    data-testid={`text-${tool.id}-description`}>
                      {tool.description}
                    </p>
                  </div>
                </div>

                <div style={{
                  fontSize: '2.5rem',
                  fontWeight: '800',
                  color: tool.color,
                  position: 'relative',
                  zIndex: 1
                }}
                data-testid={`text-${tool.id}-count`}>
                  {isLoading ? '...' : tool.count}
                </div>
                <p style={{
                  fontSize: '0.875rem',
                  color: 'hsl(var(--muted-foreground))',
                  marginTop: '0.5rem'
                }}
                data-testid={`text-${tool.id}-label`}>
                  commits pronti
                </p>
              </Card>
            );
          })}
        </div>

        {/* Recent Deployments Table */}
        <Card style={{
          background: 'rgba(255, 255, 255, 0.08)',
          backdropFilter: 'blur(24px) saturate(180%)',
          WebkitBackdropFilter: 'blur(24px) saturate(180%)',
          border: '1px solid rgba(255, 255, 255, 0.25)',
          borderRadius: '12px',
          padding: '1.5rem'
        }}>
          <h2 style={{
            fontSize: '1.5rem',
            fontWeight: '700',
            color: 'hsl(var(--foreground))',
            marginBottom: '1.5rem',
            display: 'flex',
            alignItems: 'center',
            gap: '0.5rem'
          }}
          data-testid="heading-recent-commits">
            <Clock size={24} style={{ color: 'hsl(var(--brand-orange))' }} />
            Recent Commits
          </h2>

          {isLoading ? (
            <p style={{ color: 'hsl(var(--muted-foreground))', textAlign: 'center', padding: '2rem' }} data-testid="text-loading">
              Caricamento...
            </p>
          ) : recentCommits.length === 0 ? (
            <p style={{ color: 'hsl(var(--muted-foreground))', textAlign: 'center', padding: '2rem' }} data-testid="text-no-commits">
              Nessun commit trovato
            </p>
          ) : (
            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                <thead>
                  <tr style={{ borderBottom: '1px solid rgba(255, 255, 255, 0.1)' }} data-testid="table-header-row">
                    <th style={{
                      textAlign: 'left',
                      padding: '0.75rem',
                      fontSize: '0.875rem',
                      fontWeight: '600',
                      color: 'hsl(var(--muted-foreground))'
                    }}
                    data-testid="table-header-tool">
                      Tool
                    </th>
                    <th style={{
                      textAlign: 'left',
                      padding: '0.75rem',
                      fontSize: '0.875rem',
                      fontWeight: '600',
                      color: 'hsl(var(--muted-foreground))'
                    }}
                    data-testid="table-header-resource">
                      Resource Type
                    </th>
                    <th style={{
                      textAlign: 'left',
                      padding: '0.75rem',
                      fontSize: '0.875rem',
                      fontWeight: '600',
                      color: 'hsl(var(--muted-foreground))'
                    }}
                    data-testid="table-header-version">
                      Version
                    </th>
                    <th style={{
                      textAlign: 'left',
                      padding: '0.75rem',
                      fontSize: '0.875rem',
                      fontWeight: '600',
                      color: 'hsl(var(--muted-foreground))'
                    }}
                    data-testid="table-header-status">
                      Status
                    </th>
                    <th style={{
                      textAlign: 'left',
                      padding: '0.75rem',
                      fontSize: '0.875rem',
                      fontWeight: '600',
                      color: 'hsl(var(--muted-foreground))'
                    }}
                    data-testid="table-header-created">
                      Created
                    </th>
                    <th style={{
                      textAlign: 'left',
                      padding: '0.75rem',
                      fontSize: '0.875rem',
                      fontWeight: '600',
                      color: 'hsl(var(--muted-foreground))'
                    }}
                    data-testid="table-header-type">
                      Type
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {recentCommits.map(commit => {
                    const StatusIcon = getStatusIcon(commit.status);
                    return (
                      <tr
                        key={commit.id}
                        data-testid={`row-commit-${commit.id}`}
                        style={{
                          borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
                          transition: 'background 0.2s',
                          cursor: 'pointer'
                        }}
                      >
                        <td style={{
                          padding: '0.75rem',
                          fontSize: '0.875rem',
                          color: 'hsl(var(--foreground))',
                          fontWeight: '600',
                          textTransform: 'uppercase'
                        }}
                        data-testid={`text-tool-${commit.id}`}>
                          {commit.tool}
                        </td>
                        <td style={{
                          padding: '0.75rem',
                          fontSize: '0.875rem',
                          color: 'hsl(var(--foreground))'
                        }}
                        data-testid={`text-resource-${commit.id}`}>
                          {commit.resourceType}
                        </td>
                        <td style={{
                          padding: '0.75rem',
                          fontSize: '0.875rem',
                          color: 'hsl(var(--muted-foreground))',
                          fontFamily: 'monospace'
                        }}
                        data-testid={`text-version-${commit.id}`}>
                          {commit.version}
                        </td>
                        <td style={{ padding: '0.75rem' }}>
                          <div style={{
                            display: 'inline-flex',
                            alignItems: 'center',
                            gap: '0.5rem',
                            padding: '0.25rem 0.75rem',
                            borderRadius: '9999px',
                            background: withAlpha(getStatusColor(commit.status), 0.15),
                            color: getStatusColor(commit.status),
                            fontSize: '0.75rem',
                            fontWeight: '600'
                          }}
                          data-testid={`badge-status-${commit.id}`}>
                            <StatusIcon size={14} />
                            {commit.status}
                          </div>
                        </td>
                        <td style={{
                          padding: '0.75rem',
                          fontSize: '0.875rem',
                          color: 'hsl(var(--muted-foreground))'
                        }}
                        data-testid={`text-created-${commit.id}`}>
                          {new Date(commit.createdAt).toLocaleString('it-IT')}
                        </td>
                        <td style={{
                          padding: '0.75rem',
                          fontSize: '0.75rem',
                          color: 'hsl(var(--muted-foreground))'
                        }}
                        data-testid={`text-type-${commit.id}`}>
                          {commit.autoGenerated ? (
                            <span style={{
                              background: 'hsl(var(--brand-purple) / 0.15)',
                              color: 'hsl(var(--brand-purple))',
                              padding: '0.25rem 0.5rem',
                              borderRadius: '4px',
                              fontWeight: '600'
                            }}
                            data-testid={`badge-auto-${commit.id}`}>
                              AUTO
                            </span>
                          ) : (
                            <span style={{
                              background: 'hsl(var(--muted-foreground) / 0.15)',
                              color: 'hsl(var(--muted-foreground))',
                              padding: '0.25rem 0.5rem',
                              borderRadius: '4px',
                              fontWeight: '600'
                            }}
                            data-testid={`badge-manual-${commit.id}`}>
                              MANUAL
                            </span>
                          )}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </Card>
      </div>
    </BrandLayout>
  );
}
