import { useState, useEffect } from 'react';
import { useQuery, useMutation } from '@tanstack/react-query';
import { Button } from '../ui/button';
import { Checkbox } from '../ui/checkbox';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '../ui/dialog';
import { ScrollArea } from '../ui/scroll-area';
import { 
  GitBranch, Store, Building2, ChevronRight, ChevronDown,
  AlertTriangle, CheckCircle, Package, Users, ShoppingCart, BarChart3
} from 'lucide-react';
import { queryClient } from '@/lib/queryClient';
import { useToast } from '@/hooks/use-toast';

interface DeployCommit {
  id: string;
  tool: 'crm' | 'wms' | 'pos' | 'analytics';
  resourceType: string;
  resourceId: string;
  version: string;
  status: 'pending' | 'deployed' | 'failed';
  metadata: any;
  createdAt: string;
  autoGenerated: boolean;
}

interface Branch {
  id: string;
  branchName: string;
  tenantId: string;
  pdvId: string | null;
  isMainBranch: boolean;
  lastDeployedCommitId: string | null;
  metadata: {
    type: 'tenant' | 'store';
    tenantSlug: string;
    storeSlug?: string;
    autoGenerated: boolean;
  };
}

interface DeployModalProps {
  commit: DeployCommit | null;
  open: boolean;
  onClose: () => void;
}

const withAlpha = (hslColor: string, alpha: number) => {
  if (hslColor.includes('var(')) {
    const lastParenIndex = hslColor.lastIndexOf(')');
    return hslColor.slice(0, lastParenIndex) + ` / ${alpha})`;
  } else {
    return hslColor.replace('hsl(', 'hsla(').replace(')', `, ${alpha})`);
  }
};

export default function DeployModal({ commit, open, onClose }: DeployModalProps) {
  const { toast } = useToast();
  const [selectedBranches, setSelectedBranches] = useState<Set<string>>(new Set());
  const [expandedTenants, setExpandedTenants] = useState<Set<string>>(new Set());

  const { data: branches, isLoading: branchesLoading, error: branchesError } = useQuery<{ data: Branch[] }>({
    queryKey: ['/brand-api/deploy/branches'],
    enabled: open
  });

  // Shared reset function for all close paths
  const resetState = () => {
    setSelectedBranches(new Set());
    setExpandedTenants(new Set());
  };

  // Cleanup on unmount (parent-driven closes)
  useEffect(() => {
    return () => resetState();
  }, []);

  // Safety net: reset when modal closes while component stays mounted
  useEffect(() => {
    if (!open) {
      resetState();
    }
  }, [open]);

  const deployMutation = useMutation({
    mutationFn: async (data: { commitId: string; branchIds: string[] }) => {
      const response = await fetch('/brand-api/deploy/execute', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
        credentials: 'include'
      });
      if (!response.ok) throw new Error('Deploy failed');
      return response.json();
    },
    onSuccess: () => {
      const count = selectedBranches.size; // Capture before clearing
      
      // Reset selections immediately
      resetState();
      
      toast({
        title: 'Deploy Started',
        description: `Deployment to ${count} branch(es) initiated successfully.`
      });
      queryClient.invalidateQueries({ queryKey: ['/brand-api/deploy/commits'] });
      queryClient.invalidateQueries({ queryKey: ['/brand-api/deploy/status'] });
      
      onClose(); // Parent closes
    },
    onError: (error: Error) => {
      toast({
        title: 'Deploy Failed',
        description: error.message,
        variant: 'destructive'
      });
    }
  });

  const toolIcons = {
    crm: Users,
    wms: Package,
    pos: ShoppingCart,
    analytics: BarChart3
  };

  const toolColors = {
    crm: 'hsl(25, 95%, 53%)',
    wms: 'hsl(274, 65%, 46%)',
    pos: 'hsl(142, 76%, 36%)',
    analytics: 'hsl(220, 90%, 56%)'
  };

  // Group branches by tenant
  const branchTree = branches?.data?.reduce((acc, branch) => {
    const tenantSlug = branch.metadata.tenantSlug;
    if (!acc[tenantSlug]) {
      acc[tenantSlug] = {
        mainBranch: null as Branch | null,
        pdvBranches: [] as Branch[]
      };
    }
    
    if (branch.metadata.type === 'tenant') {
      acc[tenantSlug].mainBranch = branch;
    } else {
      acc[tenantSlug].pdvBranches.push(branch);
    }
    
    return acc;
  }, {} as Record<string, { mainBranch: Branch | null; pdvBranches: Branch[] }>) || {};

  const toggleBranch = (branchId: string) => {
    setSelectedBranches(prev => {
      const newSet = new Set(prev);
      if (newSet.has(branchId)) {
        newSet.delete(branchId);
      } else {
        newSet.add(branchId);
      }
      return newSet;
    });
  };

  const toggleTenant = (tenantSlug: string) => {
    setExpandedTenants(prev => {
      const newSet = new Set(prev);
      if (newSet.has(tenantSlug)) {
        newSet.delete(tenantSlug);
      } else {
        newSet.add(tenantSlug);
      }
      return newSet;
    });
  };

  const selectAllTenantBranches = (tenantSlug: string) => {
    const tenant = branchTree[tenantSlug];
    if (!tenant) return;

    const allBranchIds = [
      tenant.mainBranch?.id,
      ...tenant.pdvBranches.map(b => b.id)
    ].filter(Boolean) as string[];

    setSelectedBranches(prev => {
      const newSet = new Set(prev);
      const allSelected = allBranchIds.every(id => newSet.has(id));
      
      if (allSelected) {
        // Deselect all
        allBranchIds.forEach(id => newSet.delete(id));
      } else {
        // Select all
        allBranchIds.forEach(id => newSet.add(id));
      }
      
      return newSet;
    });
  };

  const handleDeploy = () => {
    if (!commit || selectedBranches.size === 0) return;
    
    deployMutation.mutate({
      commitId: commit.id,
      branchIds: Array.from(selectedBranches)
    });
  };

  const ToolIcon = commit ? toolIcons[commit.tool] : Users;
  const toolColor = commit ? toolColors[commit.tool] : 'hsl(var(--muted-foreground))';

  return (
    <Dialog 
      open={open} 
      onOpenChange={(isOpen) => {
        if (!isOpen) {
          resetState(); // Clear state before parent close
          onClose();
        }
      }}
    >
      <DialogContent 
        className="max-w-4xl max-h-[90vh]"
        data-testid="modal-deploy"
      >
        <DialogHeader>
          <DialogTitle 
            className="flex items-center gap-3"
            data-testid="heading-deploy-modal"
          >
            <GitBranch size={24} style={{ color: 'hsl(var(--brand-orange))' }} />
            Deploy Commit
          </DialogTitle>
          <DialogDescription data-testid="text-deploy-description">
            Select target branches for deployment
          </DialogDescription>
        </DialogHeader>

        {!commit ? (
          <div style={{ padding: '2rem', textAlign: 'center', color: 'hsl(var(--muted-foreground))' }}>
            No commit selected
          </div>
        ) : (
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
          {/* Left Panel: Commit Details */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <div style={{
              padding: '1rem',
              background: withAlpha(toolColor, 0.1),
              borderRadius: '8px',
              border: `1px solid ${withAlpha(toolColor, 0.3)}`
            }}
            data-testid="section-commit-info">
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: '0.75rem',
                marginBottom: '1rem'
              }}>
                <div style={{
                  width: '40px',
                  height: '40px',
                  borderRadius: '8px',
                  background: withAlpha(toolColor, 0.2),
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center'
                }}>
                  <ToolIcon size={20} style={{ color: toolColor }} />
                </div>
                <div>
                  <h4 style={{
                    fontSize: '0.875rem',
                    fontWeight: '600',
                    color: 'hsl(var(--muted-foreground))'
                  }}>
                    Tool
                  </h4>
                  <p style={{
                    fontSize: '1rem',
                    fontWeight: '700',
                    color: toolColor,
                    textTransform: 'uppercase'
                  }}
                  data-testid="text-tool-name">
                    {commit?.tool || 'N/A'}
                  </p>
                </div>
              </div>

              <div style={{ fontSize: '0.875rem', color: 'hsl(var(--foreground))', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                <div>
                  <span style={{ fontWeight: '600' }}>Type:</span>{' '}
                  <span data-testid="text-resource-type">{commit?.resourceType || 'N/A'}</span>
                </div>
                <div>
                  <span style={{ fontWeight: '600' }}>Version:</span>{' '}
                  <code style={{
                    fontSize: '0.875rem',
                    padding: '0.125rem 0.375rem',
                    background: 'rgba(0, 0, 0, 0.05)',
                    borderRadius: '4px',
                    fontFamily: 'monospace'
                  }}
                  data-testid="text-commit-version">
                    {commit?.version || 'N/A'}
                  </code>
                </div>
                <div>
                  <span style={{ fontWeight: '600' }}>Created:</span>{' '}
                  <span data-testid="text-commit-created">
                    {commit?.createdAt ? new Date(commit.createdAt).toLocaleString('it-IT') : 'N/A'}
                  </span>
                </div>
                <div>
                  <span style={{ fontWeight: '600' }}>Auto-generated:</span>{' '}
                  <span data-testid="text-commit-auto">
                    {commit?.autoGenerated ? 'Yes' : 'No'}
                  </span>
                </div>
              </div>
            </div>

            {/* Impact Preview */}
            <div style={{
              padding: '1rem',
              background: selectedBranches.size > 0 
                ? withAlpha('hsl(142, 76%, 36%)', 0.1)
                : withAlpha('hsl(38, 92%, 50%)', 0.1),
              borderRadius: '8px',
              border: selectedBranches.size > 0
                ? '1px solid ' + withAlpha('hsl(142, 76%, 36%)', 0.3)
                : '1px solid ' + withAlpha('hsl(38, 92%, 50%)', 0.3)
            }}
            data-testid="section-impact-preview">
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: '0.5rem',
                marginBottom: '0.75rem'
              }}>
                {selectedBranches.size > 0 ? (
                  <CheckCircle size={20} style={{ color: 'hsl(142, 76%, 36%)' }} />
                ) : (
                  <AlertTriangle size={20} style={{ color: 'hsl(38, 92%, 50%)' }} />
                )}
                <h4 style={{
                  fontSize: '0.875rem',
                  fontWeight: '600',
                  color: 'hsl(var(--foreground))'
                }}>
                  Impact Preview
                </h4>
              </div>
              
              <div style={{ fontSize: '0.875rem', color: 'hsl(var(--foreground))' }}>
                {selectedBranches.size === 0 ? (
                  <p data-testid="text-no-branches-selected">
                    Select branches to deploy this commit
                  </p>
                ) : (
                  <div data-testid="text-branches-selected">
                    <p style={{ fontWeight: '600', marginBottom: '0.5rem' }}>
                      <span style={{ fontSize: '1.5rem', color: 'hsl(142, 76%, 36%)' }}>
                        {selectedBranches.size}
                      </span>{' '}
                      branch{selectedBranches.size !== 1 ? 'es' : ''} selected
                    </p>
                    <p style={{ fontSize: '0.75rem', color: 'hsl(var(--muted-foreground))' }}>
                      This deployment will affect the selected tenants and stores
                    </p>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Right Panel: Branch Selector Tree */}
          <div>
            <div style={{
              marginBottom: '1rem',
              paddingBottom: '0.75rem',
              borderBottom: '1px solid hsl(var(--border))'
            }}>
              <h4 style={{
                fontSize: '0.875rem',
                fontWeight: '600',
                color: 'hsl(var(--foreground))',
                marginBottom: '0.25rem'
              }}>
                Target Branches
              </h4>
              <p style={{
                fontSize: '0.75rem',
                color: 'hsl(var(--muted-foreground))'
              }}>
                Select tenant and store branches for deployment
              </p>
            </div>

            <ScrollArea style={{ height: '400px' }}>
              {branchesLoading ? (
                <div style={{
                  padding: '2rem',
                  textAlign: 'center',
                  color: 'hsl(var(--muted-foreground))'
                }}
                data-testid="text-branches-loading">
                  Loading branches...
                </div>
              ) : branchesError ? (
                <div style={{
                  padding: '2rem',
                  textAlign: 'center',
                  color: 'hsl(0, 84%, 60%)'
                }}
                data-testid="text-branches-error">
                  Failed to load branches. Please try again.
                </div>
              ) : (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                  {Object.entries(branchTree).map(([tenantSlug, tenant]) => {
                  const isExpanded = expandedTenants.has(tenantSlug);
                  const hasPDVs = tenant.pdvBranches.length > 0;
                  const allBranchIds = [
                    tenant.mainBranch?.id,
                    ...tenant.pdvBranches.map(b => b.id)
                  ].filter(Boolean) as string[];
                  const allSelected = allBranchIds.every(id => selectedBranches.has(id));
                  const someSelected = allBranchIds.some(id => selectedBranches.has(id)) && !allSelected;

                  return (
                    <div key={tenantSlug} style={{
                      border: '1px solid hsl(var(--border))',
                      borderRadius: '8px',
                      overflow: 'hidden'
                    }}
                    data-testid={`branch-tree-${tenantSlug}`}>
                      {/* Tenant Main Branch */}
                      <div style={{
                        padding: '0.75rem',
                        background: 'rgba(0, 0, 0, 0.02)',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '0.5rem'
                      }}>
                        {hasPDVs && (
                          <button
                            onClick={() => toggleTenant(tenantSlug)}
                            style={{
                              background: 'none',
                              border: 'none',
                              cursor: 'pointer',
                              padding: '0.25rem',
                              display: 'flex',
                              alignItems: 'center'
                            }}
                            data-testid={`button-toggle-${tenantSlug}`}
                          >
                            {isExpanded ? (
                              <ChevronDown size={16} style={{ color: 'hsl(var(--muted-foreground))' }} />
                            ) : (
                              <ChevronRight size={16} style={{ color: 'hsl(var(--muted-foreground))' }} />
                            )}
                          </button>
                        )}
                        {!hasPDVs && tenant.mainBranch && (
                          <Checkbox
                            checked={selectedBranches.has(tenant.mainBranch.id)}
                            onCheckedChange={() => toggleBranch(tenant.mainBranch!.id)}
                            data-testid={`checkbox-tenant-${tenantSlug}`}
                          />
                        )}
                        {hasPDVs && (
                          <Checkbox
                            checked={allSelected}
                            onCheckedChange={() => selectAllTenantBranches(tenantSlug)}
                            data-testid={`checkbox-tenant-all-${tenantSlug}`}
                            className={someSelected ? 'data-[state=checked]:bg-orange-500' : ''}
                          />
                        )}
                        <Building2 size={16} style={{ color: 'hsl(var(--brand-orange))' }} />
                        <span style={{
                          fontSize: '0.875rem',
                          fontWeight: '600',
                          color: 'hsl(var(--foreground))',
                          flex: 1
                        }}
                        data-testid={`text-tenant-${tenantSlug}`}>
                          {tenantSlug}
                          {!hasPDVs && ' (Main Branch)'}
                        </span>
                        {hasPDVs && (
                          <span style={{
                            fontSize: '0.75rem',
                            padding: '0.125rem 0.5rem',
                            background: withAlpha('hsl(var(--brand-purple))', 0.15),
                            color: 'hsl(var(--brand-purple))',
                            borderRadius: '9999px',
                            fontWeight: '600'
                          }}
                          data-testid={`badge-pdv-count-${tenantSlug}`}>
                            {tenant.pdvBranches.length} PDV{tenant.pdvBranches.length !== 1 ? 's' : ''}
                          </span>
                        )}
                      </div>

                      {/* PDV Sub-Branches */}
                      {isExpanded && hasPDVs && (
                        <div style={{
                          padding: '0.5rem',
                          paddingLeft: '2.5rem',
                          display: 'flex',
                          flexDirection: 'column',
                          gap: '0.375rem'
                        }}>
                          {tenant.pdvBranches.map((pdvBranch) => (
                            <div
                              key={pdvBranch.id}
                              style={{
                                display: 'flex',
                                alignItems: 'center',
                                gap: '0.5rem',
                                padding: '0.5rem',
                                borderRadius: '4px',
                                background: selectedBranches.has(pdvBranch.id) 
                                  ? withAlpha('hsl(var(--brand-purple))', 0.1)
                                  : 'transparent'
                              }}
                              data-testid={`branch-pdv-${pdvBranch.id}`}
                            >
                              <Checkbox
                                checked={selectedBranches.has(pdvBranch.id)}
                                onCheckedChange={() => toggleBranch(pdvBranch.id)}
                                data-testid={`checkbox-pdv-${pdvBranch.id}`}
                              />
                              <Store size={14} style={{ color: 'hsl(var(--brand-purple))' }} />
                              <span style={{
                                fontSize: '0.875rem',
                                color: 'hsl(var(--foreground))'
                              }}
                              data-testid={`text-pdv-${pdvBranch.id}`}>
                                {pdvBranch.metadata.storeSlug || pdvBranch.branchName}
                              </span>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  );
                  })}
                </div>
              )}
            </ScrollArea>
          </div>

          {/* Footer Actions */}
          <div style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginTop: '1.5rem',
            paddingTop: '1rem',
            borderTop: '1px solid hsl(var(--border))'
          }}>
          <div style={{ fontSize: '0.875rem', color: 'hsl(var(--muted-foreground))' }}>
            {selectedBranches.size > 0 && (
              <span data-testid="text-footer-count">
                {selectedBranches.size} branch{selectedBranches.size !== 1 ? 'es' : ''} ready for deployment
              </span>
            )}
          </div>
          <div style={{ display: 'flex', gap: '0.75rem' }}>
            <Button
              variant="outline"
              onClick={() => {
                resetState(); // Clear state before parent close
                onClose();
              }}
              disabled={deployMutation.isPending}
              data-testid="button-cancel-deploy"
            >
              Cancel
            </Button>
            <Button
              onClick={handleDeploy}
              disabled={selectedBranches.size === 0 || deployMutation.isPending}
              style={{
                background: selectedBranches.size > 0 
                  ? 'linear-gradient(135deg, hsl(25, 95%, 53%), hsl(25, 100%, 60%))'
                  : undefined
              }}
              data-testid="button-execute-deploy"
            >
              {deployMutation.isPending ? (
                'Deploying...'
              ) : (
                `Deploy to ${selectedBranches.size} branch${selectedBranches.size !== 1 ? 'es' : ''}`
              )}
            </Button>
          </div>
          </div>
        </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
