version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: w3suite_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
  
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"