import { useQuery } from '@tanstack/react-query';
import { Card } from '../ui/card';
import { Badge } from '../ui/badge';
import { 
  Package, Users, ShoppingCart, BarChart3, 
  Clock, GitBranch
} from 'lucide-react';

interface DeployCommit {
  id: string;
  tool: 'crm' | 'wms' | 'pos' | 'analytics';
  resourceType: string;
  resourceId: string;
  name: string;
  version: string;
  status: 'pending' | 'ready' | 'deployed' | 'failed';
  metadata: any;
  createdAt: string;
  autoGenerated: boolean;
}

export default function BrowseCommitsTab() {
  const { data: commits, isLoading } = useQuery<{ data: DeployCommit[] }>({
    queryKey: ['/brand-api/deploy/commits']
  });

  const allCommits = commits?.data || [];

  const toolColors: Record<string, string> = {
    crm: 'hsl(25, 95%, 53%)',
    wms: 'hsl(274, 65%, 46%)',
    pos: 'hsl(142, 76%, 36%)',
    analytics: 'hsl(220, 90%, 56%)',
    hr: 'hsl(340, 75%, 55%)',
  };

  const toolIcons: Record<string, any> = {
    crm: Users,
    wms: Package,
    pos: ShoppingCart,
    analytics: BarChart3,
    hr: Users,
  };

  const statusColors: Record<string, string> = {
    pending: 'hsl(38, 92%, 50%)',
    ready: 'hsl(142, 76%, 36%)',
    deployed: 'hsl(220, 90%, 56%)',
    failed: 'hsl(0, 84%, 60%)',
  };

  return (
    <div style={{ padding: '0 2rem 2rem' }}>
      <div style={{ marginBottom: '2rem' }}>
        <p style={{
          fontSize: '1rem',
          color: 'hsl(var(--muted-foreground))'
        }}>
          {allCommits.length} commit totali nel sistema
        </p>
      </div>

      {isLoading ? (
        <Card style={{
          background: 'rgba(255, 255, 255, 0.08)',
          backdropFilter: 'blur(24px) saturate(180%)',
          border: '1px solid rgba(255, 255, 255, 0.25)',
          borderRadius: '12px',
          padding: '3rem',
          textAlign: 'center'
        }}>
          <p style={{ color: 'hsl(var(--muted-foreground))' }}>
            Caricamento commit...
          </p>
        </Card>
      ) : allCommits.length === 0 ? (
        <Card style={{
          background: 'rgba(255, 255, 255, 0.08)',
          backdropFilter: 'blur(24px) saturate(180%)',
          border: '1px solid rgba(255, 255, 255, 0.25)',
          borderRadius: '12px',
          padding: '3rem',
          textAlign: 'center'
        }}>
          <GitBranch size={48} style={{ color: 'hsl(var(--muted-foreground))', margin: '0 auto 1rem' }} />
          <h3 style={{ fontSize: '1.25rem', fontWeight: '700', marginBottom: '0.5rem' }}>
            Nessun Commit
          </h3>
          <p style={{ color: 'hsl(var(--muted-foreground))' }}>
            Non ci sono commit nel sistema
          </p>
        </Card>
      ) : (
        <Card style={{
          background: 'rgba(255, 255, 255, 0.08)',
          backdropFilter: 'blur(24px) saturate(180%)',
          border: '1px solid rgba(255, 255, 255, 0.25)',
          borderRadius: '12px',
          overflow: 'hidden'
        }}>
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid rgba(255, 255, 255, 0.1)' }}>
                  <th style={{
                    textAlign: 'left',
                    padding: '1rem',
                    fontSize: '0.875rem',
                    fontWeight: '600',
                    color: 'hsl(var(--muted-foreground))',
                    background: 'rgba(255, 255, 255, 0.03)'
                  }}>
                    Tool
                  </th>
                  <th style={{
                    textAlign: 'left',
                    padding: '1rem',
                    fontSize: '0.875rem',
                    fontWeight: '600',
                    color: 'hsl(var(--muted-foreground))',
                    background: 'rgba(255, 255, 255, 0.03)'
                  }}>
                    Name
                  </th>
                  <th style={{
                    textAlign: 'left',
                    padding: '1rem',
                    fontSize: '0.875rem',
                    fontWeight: '600',
                    color: 'hsl(var(--muted-foreground))',
                    background: 'rgba(255, 255, 255, 0.03)'
                  }}>
                    Version
                  </th>
                  <th style={{
                    textAlign: 'left',
                    padding: '1rem',
                    fontSize: '0.875rem',
                    fontWeight: '600',
                    color: 'hsl(var(--muted-foreground))',
                    background: 'rgba(255, 255, 255, 0.03)'
                  }}>
                    Resource
                  </th>
                  <th style={{
                    textAlign: 'left',
                    padding: '1rem',
                    fontSize: '0.875rem',
                    fontWeight: '600',
                    color: 'hsl(var(--muted-foreground))',
                    background: 'rgba(255, 255, 255, 0.03)'
                  }}>
                    Status
                  </th>
                  <th style={{
                    textAlign: 'left',
                    padding: '1rem',
                    fontSize: '0.875rem',
                    fontWeight: '600',
                    color: 'hsl(var(--muted-foreground))',
                    background: 'rgba(255, 255, 255, 0.03)'
                  }}>
                    Created
                  </th>
                </tr>
              </thead>
              <tbody>
                {allCommits.map((commit) => {
                  const Icon = toolIcons[commit.tool];
                  const toolColor = toolColors[commit.tool];
                  const statusColor = statusColors[commit.status];

                  return (
                    <tr 
                      key={commit.id}
                      style={{ 
                        borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
                        transition: 'background 0.2s ease'
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.background = 'rgba(255, 255, 255, 0.05)';
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.background = 'transparent';
                      }}
                    >
                      <td style={{ padding: '1rem' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                          <div style={{
                            width: '32px',
                            height: '32px',
                            borderRadius: '6px',
                            background: `${toolColor}20`,
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center'
                          }}>
                            <Icon size={16} style={{ color: toolColor }} />
                          </div>
                          <Badge
                            variant="outline"
                            style={{
                              borderColor: toolColor,
                              color: toolColor,
                              textTransform: 'uppercase',
                              fontSize: '0.7rem'
                            }}
                          >
                            {commit.tool}
                          </Badge>
                        </div>
                      </td>
                      <td style={{ padding: '1rem' }}>
                        <span style={{
                          fontWeight: '600',
                          color: 'hsl(var(--foreground))'
                        }}>
                          {commit.name}
                        </span>
                      </td>
                      <td style={{ padding: '1rem' }}>
                        <Badge variant="outline">
                          v{commit.version}
                        </Badge>
                      </td>
                      <td style={{ padding: '1rem' }}>
                        <div style={{ fontSize: '0.875rem', color: 'hsl(var(--muted-foreground))' }}>
                          {commit.resourceType}
                        </div>
                      </td>
                      <td style={{ padding: '1rem' }}>
                        <Badge
                          style={{
                            background: `${statusColor}15`,
                            color: statusColor,
                            border: `1px solid ${statusColor}30`,
                            textTransform: 'capitalize'
                          }}
                        >
                          {commit.status}
                        </Badge>
                      </td>
                      <td style={{ padding: '1rem' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.875rem', color: 'hsl(var(--muted-foreground))' }}>
                          <Clock size={14} />
                          {new Date(commit.createdAt).toLocaleDateString('it-IT', {
                            day: '2-digit',
                            month: 'short',
                            year: 'numeric'
                          })}
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </Card>
      )}
    </div>
  );
}
